# Generated by Django 6.0.7 on 2026-08-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_remove_course_raiting_course_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(blank=True, null=True),
        ),
    ]
