# Generated by Django 6.0.7 on 2026-08-15 02:23

import apps.courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="order",
            field=apps.courses.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
