# Generated by Django 6.0.7 on 2026-08-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_module_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="content",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="content",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="content",
            new_name="url",
        ),
    ]
